#! /bin/sh


docker compose stop
docker compose rm -f

[ -d /data/db ] && rm -fr /data/db
[ -d /data/redis ] && rm -fr /data/redis
[ -d /data/system ] && rm -fr /data/system

echo "Create Volumes"
mkdir -p /data/db
mkdir -p /data/redis
mkdir -p /data/system

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/db \
  mastadon_db

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/nginx \
  mastadon_redis

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/system \
  mastadon_system

echo "Generate DB Password"
DB_PWD=$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 50 | head -n 1)

echo "Start DB"
docker container stop db
docker container rm db -f
docker container run --rm --name db \
            -v mastadon_db:/var/lib/postgresql/data \
            -e "POSTGRES_PASSWORD=$DB_PWD" \
            -d postgres:14-alpine

READY=1
while [ $READY != 0 ]
do
  echo "Waiting for DB"...
  sleep 5
  docker exec -it db pg_isready -U postgres
  READY=$?
done

#docker exec -it db pg_isready -U postgres
#echo "Ready: $?"

echo "Start Create DB User"
docker exec -it db psql -U postgres -c "CREATE USER mastodon WITH PASSWORD '$DB_PWD' CREATEDB;"

echo "Stop DB"
docker container stop db
docker container rm db -f

echo "Create Minimal .env.production"
cat << EOM > .env.production
DB_HOST=db
DB_PORT=5432
DB_NAME=mastodon
DB_USER=mastodon
DB_PASS=$DB_PWD
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
EOM

echo "DB Password: $DB_PWD"

#echo "Pull images"
#docker compose pull

docker compose run --rm web bundle exec rake mastodon:setup